### ISSUE TITLE
035版本模块处理图标失败

### ISSUE THREAD

**Issue by zyh941** [xudazhu1/NoticeFix#1]
开发者您好，我一直用了你的这个模块好久了，但是从今天起发现模块不再使预设的自定义图标生效，连导入的图标库也失效了，重启systemUI也没用，附件是LSP日志，麻烦帮看看是什么回事吧
[noticefix LSPosed_2023-01-20T09_14_04.133917.zip](https://github.com/xudazhu1/NoticeFix/files/10462533/noticefix.LSPosed_2023-01-20T09_14_04.133917.zip)

**Comment by xudazhu1** [comment]
你好, 不经常来这里, 有问题可以加Q 70127613 解决
